Feature/monitoring 3
DmitriySh/microservices pull request #6
Opened 2017-12-03 22:58 UTC by DmitriySh

For hw 27

2017-12-07 16:12 UTC, chromko requested changes
В целом норм, только пару вопросов нужно прояснить

2017-12-07 16:12 UTC, chromko commented on swarm/alertmanager/Dockerfile
> +ADD config.yml /etc/alertmanager/
Конфиг приложения лучше подгружать Volume'ом или механизмом docker swarm config.

2017-12-07 16:12 UTC, chromko commented on swarm/prometheus/Dockerfile
> +ADD alert.rules.yml /etc/prometheus/
то же самое по поводу конфигов внутри образов

2017-12-07 16:12 UTC, chromko commented on swarm/ui/Dockerfile_3_0
> +FROM alpine:3.6
Для чего 3 докерфайла? Почему бы не оставить один?

2017-12-07 16:12 UTC, chromko commented on swarm/docker-compose.yml
> +    image: ${USERNAME}/post:latest
почему решили убрать переменные версий образов?

2017-12-09 22:14 UTC, DmitriySh commented on swarm/ui/Dockerfile_3_0
> +FROM alpine:3.6
Проект развивает от одной темы к другой. В одном из предыдущих ДЗ была просьба проанализировать размер создаваемого образа: первый шаг для его сравнения , использовать разные базовые образы. Поэтому 3 файла.

Оставил по умолчанию один, с alpine:3.6

2017-12-09 22:17 UTC, DmitriySh commented on swarm/alertmanager/Dockerfile
> +ADD config.yml /etc/alertmanager/
1) Я не понимаю о чём вы говорите
2) Такого задания не было в описании прошлых/текущего ДЗ

2017-12-09 22:40 UTC, DmitriySh commented on swarm/docker-compose.yml
> +    image: ${USERNAME}/post:latest
Посчитал, что они бессмысленны, так как версия всего одна на всех. Вернул в .env файл

2017-12-10 00:29 UTC, DmitriySh commented on swarm/alertmanager/Dockerfile
> +ADD config.yml /etc/alertmanager/
Почитал документацию, разобрался. Внёс файлы в конфигурацию описания docker compose файла. Это действительно удобнее так как часть контейнеров просто стала использовать стандартные образы вместо самостоятельных сборок.

2017-12-10 00:32 UTC, DmitriySh commented on swarm/alertmanager/Dockerfile
> +ADD config.yml /etc/alertmanager/
развернул кластер, всё работает

2017-12-10 00:32 UTC, DmitriySh commented on swarm/prometheus/Dockerfile
> +ADD alert.rules.yml /etc/prometheus/
исправлено

2017-12-10 11:48 UTC, DmitriySh commented
Заново на проверку

2017-12-10 12:26 UTC, chromko commented
Все вопросы закрыты. Работа принята

2017-12-10 12:26 UTC, chromko approved these changes

2017-12-10 13:14 UTC, merged