Feature/kubernetes 1
DmitriySh/microservices pull request #7
Opened 2017-12-15 05:11 UTC by DmitriySh

For hw 28

2017-12-18 08:05 UTC, chromko requested changes
По hard way все ок. По Компонентам приложения - а где остальные деплойменты (mongo, ui, comment)?

2017-12-18 08:06 UTC, DmitriySh commented
> а где остальные деплойменты (mongo, ui, comment)
какие деплойменты?

2017-12-18 08:08 UTC, chromko commented
kubernetes/ui-deployment.yml
kubernetes/mongo-deployment.yml
kubernetes/comment-deployment.yml

2017-12-21 06:46 UTC, DmitriySh commented
Внёс исправления, прошу проверить работу

2017-12-22 14:15 UTC, chromko approved these changes
Теперь все ок. Работу принял

2017-12-22 14:16 UTC, merged